"""Shared plumbing: decision logging, LaTeX booktabs tables, figure style, ISO3."""

from __future__ import annotations

import re
import unicodedata
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from .config import CONFIG, OUT_DATA, OUT_FIGURES, OUT_TABLES

# ---------------------------------------------------------------- decisions --

class DecisionLog:
    """Collects every judgment call so report.md can be assembled at the end."""

    def __init__(self) -> None:
        self.entries: list[dict] = []

    def log(self, section: str, decision: str, rationale: str = "") -> None:
        self.entries.append(
            {"section": section, "decision": decision, "rationale": rationale}
        )
        print(f"  [decision:{section}] {decision}")

    def to_markdown(self, section: str | None = None) -> str:
        rows = [e for e in self.entries if section is None or e["section"] == section]
        out = []
        for e in rows:
            line = f"- **{e['section']}** — {e['decision']}"
            if e["rationale"]:
                line += f"\n  <br>*Rationale:* {e['rationale']}"
            out.append(line)
        return "\n".join(out)


LOG = DecisionLog()


# -------------------------------------------------------------------- LaTeX --

_LATEX_MAP = {
    "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
    "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}


def latex_escape(s) -> str:
    """Escape LaTeX specials and fold non-ASCII typography to safe ASCII."""
    if s is None or (isinstance(s, float) and pd.isna(s)):
        return ""
    s = str(s)
    s = (s.replace("’", "'").replace("‘", "'")
          .replace("“", "``").replace("”", "''")
          .replace("–", "--").replace("—", "---")
          .replace("…", "..."))
    # Fold remaining accents (Turkiye, Mozambique names, etc.) to ASCII.
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.encode("ascii", "replace").decode("ascii")
    return "".join(_LATEX_MAP.get(c, c) for c in s)


def write_table(
    df: pd.DataFrame,
    filename: str,
    caption: str,
    label: str,
    notes: str = "",
    align: str | None = None,
    index: bool = False,
    float_fmt: str = "{:.3f}",
    panel_col: str | None = None,
) -> Path:
    """Write a booktabs table (no vertical rules) with caption, label and notes.

    `panel_col` groups rows into labelled panels (Panel A, Panel B, ...) and drops
    the grouping column from the body.
    """
    d = df.reset_index() if index else df.copy()
    panels = None
    if panel_col and panel_col in d.columns:
        panels = list(dict.fromkeys(d[panel_col]))
        groups = {p: d[d[panel_col] == p].drop(columns=[panel_col]) for p in panels}
        d = d.drop(columns=[panel_col])

    def _row(row):
        cells = []
        for v in row:
            if isinstance(v, float) and pd.notna(v):
                cells.append(float_fmt.format(v))
            else:
                cells.append(latex_escape(v))
        return " & ".join(cells) + r" \\"

    body = []
    if panels is None:
        body = [_row(r) for _, r in d.iterrows()]
    else:
        for i, p in enumerate(panels):
            if i:
                body.append(r"\addlinespace[2pt]")
            body.append(
                rf"\multicolumn{{{len(d.columns)}}}{{l}}{{\textbf{{Panel "
                rf"{chr(65 + i)}: {latex_escape(p)}}}}} \\")
            body.append(r"\addlinespace[1pt]")
            body += [_row(r) for _, r in groups[p].iterrows()]

    if align is None:
        align = "".join(
            "r" if pd.api.types.is_numeric_dtype(d[c]) else "l" for c in d.columns
        )
    header = " & ".join(rf"\textbf{{{latex_escape(c)}}}" for c in d.columns) + r" \\"

    ncol = len(d.columns)
    # Wide tables get a smaller body and tighter column separation so they still
    # fit the text block of a portrait page without \resizebox.
    size = r"\footnotesize" if ncol >= 8 else r"\small"
    lines = [
        r"% Auto-generated by analysis.pipeline -- do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{latex_escape(caption)}}}",
        rf"\label{{{label}}}",
        size,
    ]
    if ncol >= 8:
        lines.append(r"\setlength{\tabcolsep}{3.5pt}")
    # Shrink to the text block only when the natural width exceeds it, so a table
    # that already fits is never blown up. Applied to every table so that adding
    # an outcome, cluster or phase to CONFIG can never push one off the page.
    # Requires graphicx.
    lines.append(r"\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{%")
    lines += [
        rf"\begin{{tabular}}{{{align}}}",
        r"\toprule",
        header,
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
    ]
    lines.append(r"}")
    if notes:
        lines += [
            r"\begin{minipage}{\textwidth}\vspace{2mm}\footnotesize",
            latex_escape(notes),
            r"\end{minipage}",
        ]
    lines += [r"\end{table}", ""]

    path = OUT_TABLES / filename
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {path.relative_to(path.parents[2])}  ({len(d)} rows x {ncol} cols)")
    return path


def write_data(df: pd.DataFrame, filename: str, index: bool = False) -> Path:
    path = OUT_DATA / filename
    df.to_csv(path, index=index, encoding="utf-8")
    print(f"  wrote {path.relative_to(path.parents[2])}  ({len(df)} rows)")
    return path


# ------------------------------------------------------------------ figures --

def set_style() -> None:
    plt.rcParams.update({
        "figure.dpi": 110,
        "savefig.dpi": CONFIG["DPI"],
        "savefig.bbox": "tight",
        "font.family": "DejaVu Sans",
        "font.size": 8,
        "axes.titlesize": 9,
        "axes.labelsize": 8,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "grid.linewidth": 0.5,
        "legend.frameon": False,
        "legend.fontsize": 7,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "lines.linewidth": 1.4,
    })


def save_fig(fig, filename: str) -> Path:
    path = OUT_FIGURES / filename
    fig.savefig(path, dpi=CONFIG["DPI"], bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"  wrote {path.relative_to(path.parents[2])}")
    return path


def cluster_colors(n: int) -> list[str]:
    pal = CONFIG["PALETTE"]
    return [pal[i % len(pal)] for i in range(n)]


# Candidate label offsets in points, tried in order: centred, then a ring.
_OFFSETS = [(0, 0), (0, 7), (0, -7), (8, 0), (-8, 0), (7, 5), (-7, 5),
            (7, -5), (-7, -5), (0, 12), (0, -12), (13, 0), (-13, 0)]


def place_labels(ax, xy, texts, priority=None, fontsize=5.2, color="black",
                 leader_from=None, avoid_center=False, occupied=None, **kw):
    """Annotate points, nudging labels off each other and drawing leader lines.

    Greedy: high-priority labels claim their preferred slot first, later ones
    take the nearest free ring position. Overlap is tested on real rendered
    extents, so it is exact rather than an estimate from string length.

    Pass the returned `occupied` list into a later call to keep successive label
    sets from colliding with each other.
    """
    fig = ax.figure
    order = (range(len(texts)) if priority is None
             else sorted(range(len(texts)), key=lambda i: -priority[i]))
    arts = []
    placed = occupied if occupied is not None else []
    fig.canvas.draw()
    rend = fig.canvas.get_renderer()

    # avoid_center keeps a label off its own marker (used where the marker
    # itself carries meaning, e.g. the code triangles on the CA map).
    offsets = _OFFSETS[1:] if avoid_center else _OFFSETS
    for i in order:
        x, y = xy[i]
        best, best_bb, best_pen = offsets[0], None, None
        for off in offsets:
            t = ax.annotate(texts[i], (x, y), textcoords="offset points", xytext=off,
                            fontsize=fontsize, ha="center", va="center", color=color,
                            **kw)
            bb = t.get_window_extent(rend)
            pen = sum(bb.overlaps(p) for p in placed) * 100 + abs(off[0]) + abs(off[1])
            t.remove()
            if best_pen is None or pen < best_pen:
                best, best_bb, best_pen = off, bb, pen
            if pen < 100:      # first collision-free slot wins; ring is ordered
                break
        t = ax.annotate(texts[i], (x, y), textcoords="offset points", xytext=best,
                        fontsize=fontsize, ha="center", va="center", color=color, **kw)
        placed.append(best_bb)
        arts.append(t)
        if leader_from is not None and (abs(best[0]) + abs(best[1])) >= 12:
            t.set_arrowprops = None
            ax.annotate("", xy=(x, y), xytext=best, textcoords="offset points",
                        arrowprops=dict(arrowstyle="-", lw=0.4,
                                        color=leader_from, shrinkA=0, shrinkB=0))
    return placed


# --------------------------------------------------------------------- ISO3 --

ISO3 = {
    "Albania": "ALB", "Algeria": "DZA", "Argentina": "ARG", "Armenia": "ARM",
    "Australia": "AUS", "Austria": "AUT", "Bahrain": "BHR", "Bangladesh": "BGD",
    "Belgium": "BEL", "Bolivia": "BOL", "Brazil": "BRA", "Brunei Darussalam": "BRN",
    "Cabo Verde": "CPV", "Cambodia": "KHM", "Cameroon": "CMR", "Canada": "CAN",
    "Chile": "CHL", "China": "CHN", "Colombia": "COL", "Croatia": "HRV",
    "Cuba": "CUB", "Czechia": "CZE", "Denmark": "DNK", "Ecuador": "ECU",
    "Egypt": "EGY", "Finland": "FIN", "France": "FRA", "Gabon": "GAB",
    "Germany": "DEU", "Ghana": "GHA", "Greece": "GRC", "Guatemala": "GTM",
    "Guyana": "GUY", "Holy See": "VAT", "Hungary": "HUN", "Iceland": "ISL",
    "India": "IND", "Indonesia": "IDN", "Iran": "IRN", "Iraq": "IRQ",
    "Ireland": "IRL", "Israel": "ISR", "Italy": "ITA", "Jamaica": "JAM",
    "Japan": "JPN", "Jordan": "JOR", "Kazakhstan": "KAZ", "Kuwait": "KWT",
    "Kyrgyzstan": "KGZ", "Lao People's Democratic Republic": "LAO",
    "Lebanon": "LBN", "Libya": "LBY", "Liechtenstein": "LIE", "Luxembourg": "LUX",
    "Malaysia": "MYS", "Maldives": "MDV", "Malta": "MLT", "Mauritania": "MRT",
    "Mexico": "MEX", "Morocco": "MAR", "Mozambique": "MOZ", "Namibia": "NAM",
    "Netherlands": "NLD", "New Zealand": "NZL", "Nicaragua": "NIC",
    "Nigeria": "NGA", "Norway": "NOR", "Oman": "OMN", "Pakistan": "PAK",
    "Palestine": "PSE", "Panama": "PAN", "Peru": "PER", "Philippines": "PHL",
    "Poland": "POL", "Portugal": "PRT", "Qatar": "QAT",
    "Republic of Korea": "KOR", "Romania": "ROU", "Russian Federation": "RUS",
    "Saint Lucia": "LCA", "Saudi Arabia": "SAU", "Senegal": "SEN",
    "Serbia": "SRB", "Sierra Leone": "SLE", "Slovenia": "SVN", "Somalia": "SOM",
    "South Africa": "ZAF", "Spain": "ESP", "Sri Lanka": "LKA",
    "Switzerland": "CHE", "Syrian Arab Republic": "SYR", "Thailand": "THA",
    "Timor-Leste": "TLS", "Trinidad and Tobago": "TTO", "Tunisia": "TUN",
    "Turkiye": "TUR", "Uganda": "UGA", "Ukraine": "UKR",
    "United Arab Emirates": "ARE", "United Kingdom": "GBR",
    "United States": "USA", "Venezuela": "VEN", "Viet Nam": "VNM", "Yemen": "YEM",
}


def _norm_country(name: str) -> str:
    s = str(name).replace("’", "'").strip()
    s = unicodedata.normalize("NFKD", s)
    return "".join(c for c in s if not unicodedata.combining(c))


def iso3(name: str) -> str:
    """ISO3 code for a UN country name; falls back to a 3-letter stub."""
    key = _norm_country(name)
    if key in ISO3:
        return ISO3[key]
    stub = re.sub(r"[^A-Za-z]", "", key).upper()[:3]
    return stub or "UNK"


def ensure_dirs() -> None:
    for d in (OUT_TABLES, OUT_FIGURES, OUT_DATA):
        d.mkdir(parents=True, exist_ok=True)
