"""Assemble outputs/report.md from the decision log and the analysis results."""

from __future__ import annotations

import pandas as pd

from .config import CONFIG, OUT
from .event_study import CAVEAT
from .io_utils import LOG


def _code(col: str) -> str:
    """Display name for a fingerprint column, keeping the dimension on absence
    categories so the two identical NONE_ABSENT columns stay distinguishable."""
    dim, code = col.split("__", 1)
    return f"{dim}:none" if code.endswith("NONE_ABSENT") else code


def write_report(corpus, fp, cl, mp, sg, ph, es, sn) -> None:
    span = corpus.model_span
    u, ms = corpus.units, corpus.member_states
    L: list[str] = []

    L += ["# Analysis report", "",
          "UN Security Council debates on the question of Palestine, annotated with five "
          "Galtung-style codebooks. This file records every judgment call the pipeline "
          "made; `data_report.md` records the Phase 0 schema mapping and validation in "
          "detail. Everything here is regenerated by `python -m analysis.pipeline`.", ""]

    # ---------------------------------------------------------------- summary
    L += ["## 0. What the analysis found", "",
          f"- **Corpus.** {len(u):,} non-procedural paragraphs, {u.speech_id.nunique():,} "
          f"speeches, {u.meeting_id.nunique()} meetings, "
          f"{u.date.min().date()} to {u.date.max().date()}. All 27 sanity checks "
          "reproduce the expected counts exactly.",
          f"- **Population.** {len(ms):,} paragraphs from {ms.country.nunique()} member "
          f"states in national capacity; {len(fp['n'])} states clear the pooled floor of "
          f"{CONFIG['MIN_PARAGRAPHS_POOLED']} paragraphs and enter the typology.",
          f"- **Typology (RQ2).** k={cl['k']} clusters, both bootstrap-stable "
          f"(mean Jaccard "
          + " and ".join(f"{r.mean_jaccard:.2f}" for r in cl["stability"].itertuples())
          + ").",
          f"- **Map (RQ1).** The first correspondence-analysis axis carries "
          f"{mp['inertia'][0]:.1%} of inertia and is the axis the clusters sit on.",
          f"- **Movement.** {len(ph['movers'])} states change cluster between phases; "
          "consecutive-phase ARI "
          + (", ".join(f"{r['ARI']:.2f}" for _, r in ph["ari"].iterrows())
             if len(ph["ari"]) else "n/a") + ".", ""]

    # -------------------------------------------------------------- RQ answers
    sig = sg["signatures"]
    L += ["### The two definitions of peace", "",
          "Read from `table_cluster_signatures.tex`; the labels below are **DRAFT** and "
          "must be revised after close reading.", ""]
    for g in sorted(sig.cluster.unique()):
        s = sig[sig.cluster == g]
        top = s.nlargest(5, "v_test")
        members = cl["assign"][cl["assign"].cluster == g].iso3.tolist()
        L += [f"**C{g}** ({len(members)} states) — over-represented: "
              + ", ".join(f"`{_code(r.code)}` "
                          f"({r.cluster_share:.2f} vs {r.corpus_share:.2f}, "
                          f"v={r.v_test:+.1f})" for r in top.itertuples()) + ".",
              "",
              "  " + ", ".join(sorted(members)), ""]

    # ----------------------------------------------------------------- k choice
    L += ["## 1. Choice of $k$ and cluster stability", "",
          f"**k = {cl['k']}.** {cl['rule']}.", "",
          "| k | Silhouette | Min cluster size | Min Jaccard | Unstable clusters |",
          "|---|---|---|---|---|"]
    for r in cl["diag"].itertuples():
        L.append(f"| {int(r.k)}{' **<-**' if int(r.k) == cl['k'] else ''} | "
                 f"{r.silhouette:.3f} | {int(r.min_cluster_size)} | "
                 f"{getattr(r, 'min_jaccard', float('nan')):.3f} | "
                 f"{int(getattr(r, 'n_unstable', 0))} |")
    L += ["", "Silhouette on its own would also have chosen k=2, but it is not a "
          "sufficient criterion: it always favours the coarsest split and says nothing "
          "about reproducibility. The bootstrap screen is what rules out the finer "
          "partitions — k=3 splits the larger cluster into a 23/18 pair whose weaker "
          "half is recovered in only about half of resamples. The k=3 substructure is "
          "reported in `table_k_selection.tex` and is worth inspecting substantively, "
          "but it is not stable enough to carry a typology.", "",
          f"Full bootstrap at k={cl['k']} ({CONFIG['BOOTSTRAP_B']} resamples, paragraphs "
          "resampled within country):", "",
          "| Cluster | Countries | Mean Jaccard | SD | P(J >= 0.75) | Stable |",
          "|---|---|---|---|---|---|"]
    for _, r in cl["stability"].iterrows():
        L.append(f"| C{r['cluster']} | {r['n_countries']} | {r['mean_jaccard']:.3f} | "
                 f"{r['sd_jaccard']:.3f} | {r['p_recovered_0.75']:.3f} | "
                 f"{'yes' if r['stable'] else '**NO**'} |")
    unstable = cl["stability"][~cl["stability"].stable]
    L += ["", ("No cluster falls below the 0.60 stability floor."
               if not len(unstable) else
               "**Unstable clusters flagged: "
               + ", ".join(f"C{c}" for c in unstable.cluster) + ".**"), ""]

    # ----------------------------------------------------------- network check
    L += ["## 2. Do the network communities agree with the clusters?", "",
          f"Louvain on the k=5 cosine kNN graph finds {mp['n_communities']} communities "
          f"against {cl['k']} Ward clusters; ARI = **{mp['ari_ward_louvain']:.3f}**.", ""]
    if mp["ari_ward_louvain"] < 0.7:
        L += ["**The two partitions agree only partially, and this is stated explicitly "
              "as required.** But the ARI understates the agreement, and it is worth "
              "being precise about why."]
        if mp.get("nested"):
            L += ["", "Every Louvain community lies entirely inside a single Ward "
                  "cluster:", "",
                  "| Community | Countries | Contained in |", "|---|---|---|"]
            for c, n, w in mp["nesting"]:
                L.append(f"| {c} | {n} | C{w[0]} |")
            L += ["", "So the disagreement is one of **resolution, not of structure**: "
                  "Louvain subdivides the Ward clusters, it never cuts across them. "
                  "Modularity on a sparse 5-nearest-neighbour graph rewards finer "
                  "communities, while Ward minimises within-cluster variance in the full "
                  "30-dimensional CLR space; ARI penalises that difference in grain "
                  "heavily even when the coarse partition is reproduced exactly. The Ward "
                  "solution is carried forward because it is the one with a bootstrap "
                  "warrant, and the k=2 split it encodes is recovered by the network "
                  "method as well.", ""]
        else:
            n_split = sum(1 for _, _, w in mp["nesting"] if len(w) > 1)
            L += ["", f"{n_split} of {mp['n_communities']} communities straddle Ward "
                  "clusters, so the two methods genuinely cut across each other here. "
                  "This is a real inconsistency in the typology and should be weighed "
                  "before treating the Ward clusters as settled.", ""]
    else:
        L += ["The two partitions agree closely.", ""]

    # ------------------------------------------------------------------ phases
    L += ["## 3. Phases", "", "Configured phases, and what the data forced:", "",
          "| Phase (final) | Start | End | Meetings | Paragraphs |", "|---|---|---|---|---|"]
    for name, (s, e) in corpus.phases.items():
        sub = u[u.phase == name]
        L.append(f"| `{name}` | {s.date()} | {e.date()} | {sub.meeting_id.nunique()} | "
                 f"{len(sub):,} |")
    L += ["", "Merges applied by the auto-merge rule (< "
          f"{CONFIG['PHASE_MIN_MEETINGS']} meetings or < "
          f"{CONFIG['PHASE_MIN_PARAGRAPHS']:,} paragraphs):", ""]
    merges = [e for e in LOG.entries if e["section"] == "phases"
              and e["decision"].startswith("Auto-merge")]
    L += ([f"- {e['decision'].replace('Auto-merge: ', '')}" for e in merges]
          or ["- none"])
    L += ["", "**The corpus ends 2025-09-29, not December 2025.** Two consequences:", "",
          "1. `P5_ceasefire_2` (2025-10-10 to 2025-12-31) contains **zero meetings** and "
          "was merged away. There is no second-ceasefire period in these data, so no "
          "second-ceasefire finding can be made.",
          "2. `P3_ceasefire_1` has 7 meetings and 1,237 paragraphs — just under both "
          "floors — and was therefore merged into its neighbour. This is the costliest "
          "automatic decision in the run: it dissolves the ceasefire / resumed-war "
          "contrast, which is the most interesting within-2025 comparison available. "
          "Setting `PHASE_MIN_MEETINGS: 7` and `PHASE_MIN_PARAGRAPHS: 1200` in CONFIG "
          "would preserve P3 as its own phase. The event study for E2 is unaffected: it "
          "uses the *original* CONFIG boundaries, so its post window still stops at "
          "2025-03-17 when the war resumes.", "",
          f"A further {int((u.phase == 'outside').sum())} paragraphs "
          f"({u[u.phase == 'outside'].meeting_id.nunique()} meetings, 2023-08-21 and "
          "2023-09-27) predate every phase window. They are kept in the pooled analysis "
          "and excluded from phase-level analysis rather than folded into a phase called "
          "'war onset', which they precede.", ""]

    if len(ph["ari"]):
        L += ["Consecutive-phase agreement after aligning phase clusters to the pooled "
              "typology by centroid matching:", "",
              "| From | To | Countries in both | ARI | Same cluster |",
              "|---|---|---|---|---|"]
        for _, r in ph["ari"].iterrows():
            L.append(f"| {r['Phase A']} | {r['Phase B']} | {r['Countries in both']} | "
                     f"{r['ARI']:.3f} | {r['Same cluster']:.0%} |")
        L += ["", "The typology is close to stationary: the great majority of states hold "
              "the same position throughout, and movement is concentrated in a handful of "
              "states listed in `table_phase_membership_movers.tex`.", ""]

    # ------------------------------------------------------ transcend / model
    L += ["## 4. The transcend annotation-model switch", ""]
    if span["split"]:
        pm = span["per_model"]
        L += ["| Model | Paragraphs | First | Last |", "|---|---|---|---|"]
        for r in pm.itertuples():
            L.append(f"| `{r.model}` | {r.paragraphs:,} | {r.start.date()} | "
                     f"{r.end.date()} |")
        L += ["", "The split **is temporal**, and almost cleanly so: assigning each "
              "meeting its modal model yields three contiguous runs, not an interleaving. "
              f"The largest single-model span is `{span['model']}`, "
              f"**{span['start'].date()} to {span['end'].date()}** — {span['meetings']} "
              f"meetings, {span['paragraphs']:,} paragraphs, {span['purity']:.1%} pure. "
              "Six meetings are internally mixed; within the span, the 0.6% of paragraphs "
              "annotated by the other model are dropped.", "",
              "Where the policy was applied:", "",
              "| Use | Policy |", "|---|---|",
              "| Pooled fingerprints, CA map, Ward clustering | Both models combined. "
              "Cross-sectional, no time comparison. |",
              "| `fig_code_trends.png`, transcend panel | Restricted to the span; the "
              "rest of the timeline is greyed out. |",
              "| Phase re-clustering | Both models combined (cross-sectional within "
              "phase); phase-to-phase ARI should be read with this in mind. |",
              "| Event studies on `transformative_framing` | Span only; a cell whose "
              "observed window crosses the boundary is skipped. |",
              "| Sensitivity variant (c) | Transcend restricted to the span, other "
              "dimensions untouched. |", "",
              "No regression carries a model indicator, because in every regression that "
              "touches transcend the span restriction has already reduced the sample to a "
              "single model, which makes the indicator collinear with the constant.", ""]
    else:
        L += ["Only one annotation model is present.", ""]

    # ------------------------------------------------------------ event study
    L += ["## 5. Event studies", "", "| Event | Outcome | post | SE | 95% CI | N | "
          "Countries |", "|---|---|---|---|---|---|---|"]
    for _, r in es["table"].iterrows():
        b = "skipped" if pd.isna(r["post coef"]) else f"{r['post coef']:+.4f}"
        se = "" if pd.isna(r["Clustered SE"]) else f"{r['Clustered SE']:.4f}"
        L.append(f"| {r['Event']} | {r['Outcome']} | {b} | {se} | {r['95% CI']} | "
                 f"{int(r['N paragraphs']):,} | {int(r['N countries'])} |")
    L += [""]
    if es["skipped"]:
        L += ["Skipped cells: " + "; ".join(f"`{s}`" for s in es["skipped"]) + ".", ""]
    L += ["> **Caveat.** " + CAVEAT, "",
          "This caveat is also printed as a note under `table_event_study.tex`.", "",
          "Two implementation notes. First, the post window truncates at the next "
          "boundary of the **original** CONFIG phases rather than the merged ones, since "
          "the merge is a sample-size fix for clustering while the truncation exists to "
          "keep the post window inside one substantive period. Second, the "
          "country-meeting aggregated WLS returns a point estimate identical to the "
          "paragraph-level LPM. That is not a coding error: every regressor is constant "
          "within a country-meeting cell, so weighted group-means regression is "
          "algebraically the same estimator. It is retained as a check on the standard "
          "errors, and the report of it as a robustness check on the coefficient should "
          "be understood in that light.", ""]

    # ------------------------------------------------------------ sensitivity
    L += ["## 6. Sensitivity", "",
          "| Variant | Countries | ARI vs main | Verdict |", "|---|---|---|---|"]
    for _, r in sn["table"].iterrows():
        L.append(f"| {r['Variant']} | {r['Countries']} | {r['ARI vs main']:.3f} | "
                 f"{r['Verdict']} |")
    L += [""]
    for _, r in sn["table"].iterrows():
        L.append(f"- **{r['Variant']}** — {r['_desc']}. ARI {r['ARI vs main']:.3f}: "
                 + ("the typology holds; the same states fall on the same side of the "
                    "same divide." if r["ARI vs main"] >= 0.8 else
                    "the typology largely holds, with a minority of states reassigned."
                    if r["ARI vs main"] >= 0.6 else
                    "**the typology does not survive this variant** and the headline "
                    "result should be treated as conditional on the main filter set."))
    L += ["", "Variants (a) and (b) are weak tests and should be read as such: "
          f"{(corpus.ann.confidence >= CONFIG['CONFIDENCE_SENS']).mean():.1%} of "
          "annotations already clear the confidence threshold (self-reported confidence "
          "is concentrated on 0.8 and 0.9) and "
          f"{(corpus.ann.evidence_verified == 1).mean():.1%} already have a verified "
          "evidence span. Neither filter removes enough of the data to move the "
          "solution. Variant (c) is the substantive one.", ""]

    # ------------------------------------------------------------- decisions
    L += ["## 7. Every logged decision", ""]
    seen = []
    for e in LOG.entries:
        if e["section"] not in seen:
            seen.append(e["section"])
    for sec in seen:
        L += [f"### {sec}", "", LOG.to_markdown(sec), ""]

    # -------------------------------------------------------------- check list
    codebook_state = ("the codebooks **were** found in `codebooks/*.yaml`, so codes carry "
                      "human-readable labels throughout"
                      if corpus.codebooks_found else
                      "no codebooks were found, so raw code IDs are used and "
                      "`transformative_framing` is UNVERIFIED")
    L += ["## 8. Verify by hand", "",
          "In priority order.", "",
          "1. **The `transformative_framing` outcome definition — T2+T3+T4.** This is the "
          "one CONFIG definition I think is wrong, and it is flagged `verify: True` in "
          "CONFIG for good reason. " + codebook_state.capitalize() + ". The transcend "
          "codebook's own theory field states Galtung's five conflict outcomes — one "
          "party prevails, the other prevails, withdrawal, **compromise**, and "
          "**transcendence** — as distinct categories, and defines `T2` as "
          "\"Compromise: ONLY mutual exchange to reach the middle point\" against `T4` "
          "\"Both/And (Transcend): both parties achieve their main goals simultaneously "
          "(creative solution)\". In the TRANSCEND method compromise is precisely *not* "
          "transcendence; it is the midpoint each party concedes toward. Folding T2 in "
          "with T3 and T4 therefore measures \"at or above the midpoint of the "
          "either/or -- both/and scale\", which is a defensible quantity but is not "
          "transformative framing. **The pipeline runs the CONFIG definition as "
          "specified** and additionally carries a strict variant "
          "(`OUTCOME_VARIANTS['transformative_framing']` = T3+T4) for you to compare. "
          "Decide which one the paper should report.",
          "",
          "2. **The phase dates, and especially the missing P5.** `P5_ceasefire_2` covers "
          "2025-10-10 to 2025-12-31 and the corpus stops on 2025-09-29, so that phase is "
          "empty. Either the brief's end date is wrong or a batch of late-2025 meetings "
          "is missing from the database. This is worth resolving before anything is "
          "written about the second ceasefire. Check also whether "
          "`P3_ceasefire_1` should be protected from the auto-merge (see section 3).",
          "",
          "3. **The event dates.** `E1_icj_orders = 2024-01-26` and "
          "`E2_ceasefire_1 = 2025-01-19` are taken from CONFIG unverified. E1 matches the "
          "ICJ provisional-measures order in *South Africa v. Israel*; confirm E2 against "
          "the date the first ceasefire actually took effect rather than the date it was "
          "announced, since the windows are anchored on it.",
          "",
          "4. **The DRAFT cluster labels.** `table_cluster_draft_labels.tex` is generated "
          "mechanically from signature codes. Read "
          "`outputs/data/quotes_reading_sample.csv` "
          f"({len(sg['reading_sample'])} paragraphs, stratified by cluster and phase) and "
          "rewrite them. Nothing downstream computes on that file.",
          "",
          "5. **The presidency rule.** Speeches with `role='president'` are counted as "
          "national-capacity statements when they carry an explicit marker or run to at "
          "least 4 non-procedural paragraphs. The threshold is justified empirically in "
          "`data_report.md` section 6.2, but it is a threshold, and it governs "
          f"{int((u.role_raw == 'president').sum())} paragraphs.",
          "",
          "6. **Group-statement detection.** "
          f"{len(corpus.group_speeches)} group deliveries are detected, of which "
          f"{int((corpus.group_speeches.classified_as == 'group_rep').sum())} are removed "
          "from the member-state population (the rest are delivered by briefers and were "
          "already outside it). They are listed individually in `data_report.md` "
          "section 6.1. The detector distinguishes *delivering* a group statement from "
          "*aligning with* one; spot-check it.",
          "",
          "7. **The duplicated absence category.** `attribution__NONE_ABSENT` is "
          "identical to `violence_type__NONE_ABSENT` in all "
          f"{len(ms):,} member-state paragraphs, because `attribution` is "
          "`conditional_on` `violence_type` in the codebook. The brief asks for a none "
          "share in each of the six dimensions, so both are kept, which gives that one "
          "feature double weight in the Euclidean distance. Sensitivity variant (d) drops "
          "the duplicate; see section 6 for how much it matters.",
          "",
          "8. **The attribution denominator.** `attribution_israel` is computed over "
          "paragraphs carrying *any* attribution code, and the codebook makes explicit "
          "`NONE` (violence coded, no actor named) one of those codes. If the intended "
          "quantity is \"when a state assigns blame, how often to Israel\", the "
          "denominator should be ATR-ISR + ATR-PAL only. The two differ materially: "
          f"{int((corpus.ann.dimension == 'attribution').sum()):,} attribution "
          f"annotations, of which "
          f"{int(((corpus.ann.dimension == 'attribution') & (corpus.ann.value == 'NONE')).sum()):,} "
          "are explicit NONE.", ""]

    L += ["## 9. Outputs", "",
          "Tables are `\\input`-ready and need this in the preamble:", "",
          "```latex",
          "\\usepackage{booktabs}   % \\toprule / \\midrule / \\bottomrule",
          "\\usepackage{array}      % p{} columns in the membership tables",
          "\\usepackage{graphicx}   % \\resizebox width guard",
          "```", "",
          "Each table carries its own `\\caption` and `\\label`, uses no vertical rules, "
          "and is wrapped in a shrink-only-if-needed `\\resizebox`, so none overflows the "
          "text block. All 12 compile with zero overfull boxes in an 11pt article on "
          "letter paper with 1-inch margins.", "",
          "Figures are 300 dpi PNG on the Okabe-Ito colourblind-safe palette with ISO3 "
          "country labels. They are sized for a full text-width column (about 7 inches); "
          "`fig_ca_map`, `fig_similarity_network` and `fig_coclustering_heatmap` place 70 "
          "labelled countries each and will not survive being shrunk to a narrow "
          "two-column measure.", "",
          "| Kind | Files |", "|---|---|",
          "| Tables (`outputs/tables/`) | "
          + ", ".join(f"`{p.name}`" for p in sorted((OUT / "tables").glob("*.tex"))) + " |",
          "| Figures (`outputs/figures/`) | "
          + ", ".join(f"`{p.name}`" for p in sorted((OUT / "figures").glob("*.png"))) + " |",
          "| Data (`outputs/data/`) | "
          + ", ".join(f"`{p.name}`" for p in sorted((OUT / "data").glob("*.csv"))) + " |",
          ""]

    (OUT / "report.md").write_text("\n".join(L), encoding="utf-8")
    print("  wrote outputs/report.md")
